### ISSUE TITLE
Should the order of the arguments of verify and verify_and_update be swapped?

### ISSUE THREAD

**Issue by hasB4K** [frankie567/pwdlib#2]
Hello @frankie567,

First, thank you for this project! The fact that passlib is being unmaintained is clearly a bad sign... The fact that you decided to create an alternative is a great news!

I was integrating this lib as a PasswordHelper in `fastapi-users`. I noticed that the order of the `hashed_password` and `plain_password` are reversed when comparing against passlib. Is that something you would like to change to have a drop in replacement?

see:

https://github.com/frankie567/pwdlib/blob/2a847c1131a37eeffa1a47924eccf0dd4c3c3839/pwdlib/_hash.py#L91

and:

https://foss.heptapod.net/python-libs/passlib/-/blob/branch/stable/passlib/context.py?ref_type=heads#L2349

**Comment by hasB4K** [comment]
Here is the code of the PasswordHelper using pwdlib for fastapi-users: https://github.com/fastapi-users/fastapi-users/issues/1325#issuecomment-1979832994

**Comment by frankie567** [comment]
Good catch! I was probably lead to that way when I wrapped the Argon2 API:

https://github.com/frankie567/pwdlib/blob/153a7346aaa8c791d032a244396eed93ed93f3a5/pwdlib/hashers/argon2.py#L55-L64

But yes, I think it's probably good to follow Passlib style :)
