### ISSUE TITLE
question on defaults for argon2

### ISSUE THREAD

**Issue by 84adam** [frankie567/pwdlib#3]
Are the defaults for argon2 in pwdlib documented anywhere? I can't seem to find them in docs or source code.

```
from pwdlib import PasswordHash
password_hash = PasswordHash.recommended()
password_hash.hash("herminetincture")
```

example output structure: `$argon2id$v=19$m=65536,t=3,p=4$<hashedpw>`

^ from the above I assume version=19; memory=65536 kibibytes; iterations=3; parallelism=4. Is this correct?

**Comment by frankie567** [comment]
The defaults are actually pulled directly from Argon2 implementation:

https://github.com/frankie567/pwdlib/blob/17fd0c6a2f4b18cdc5fe6d8115844b7aea4cbfce/pwdlib/hashers/argon2.py#L15-L23

Which are defined there, and corresponds to the "low memory" profile of the RFC:

https://github.com/hynek/argon2-cffi/blob/0805dbdded04dc3c4bc8573236c80be50ff30113/src/argon2/profiles.py#L30-L38
