### ISSUE TITLE
Relax hashing packages requirements

### ISSUE THREAD

**Issue by MrNaif2018** [frankie567/pwdlib#8]
Hi! Thank you very much for your package!
Is it possible to relax requirements for hashing packages, in order to e.g. avoid doing a new release each time when a new version of bcrypt or argon2-cffi is released? For example bcrypt already issued a few releases but here it's pinned at https://github.com/frankie567/pwdlib/blob/b2f0945bab30603640c275100efd9423d4f134ce/pyproject.toml#L86
I don't think they should break their API in any distant future as well
Thank you!

**Comment by frankie567** [comment]
Yes, good call! Let's do this :)
